<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $document_name; ?></title>
    <link rel="stylesheet" href="/css/app.css">

</head>
<body>

    <?php if($document_name !== "Login"): ?>

        <nav>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/authors">Authors</a></li>
                <li><a href="#">Add a book</a></li>
                <li><a href="/logout">Logout</a></li>
            </ul>
        </nav>

    <?php endif; ?>   

    <div class="container">
        <?php include $file; ?>
    </div>

</body>
</html>