<?php 
Qss\Includes\Session::destroy();
Qss\Includes\Cookie::unset("cookie_token");

echo isset($error_message) ? $error_message : ''; 

?>
<form action="/login/store-token" method="POST">
  
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" placeholder="Enter email" name="email">
    </div>
    

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" placeholder="Enter password" name="password">
    </div>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember_me"> Remember me
    </label>
  
</form>