<form action="/login/store-token" method="POST">
  
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" placeholder="Enter email" name="email">
    </div>
    

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" placeholder="Enter password" name="password">
    </div>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  
</form>