<?php if(empty($authors)): ?>
  <p>There is no authors</p>
  <?php else: ?>
<div>
    <p>Total results: <?php echo $meta["total_results"]; ?></p>
</div>

<table>
  <tr>
    <th>ID</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Birthday</th>
    <th>Gender</th>
    <th>Place of birth</th>
    <th>Delete</th>
  </tr>
  <?php foreach ($authors as $author): ?>
    <tr>
        <td> <a href="/authors/<?php echo $author["id"]; ?>"><?php echo $author["id"]; ?></a></td>
        <td>  <?php echo $author["first_name"]; ?></td>
        <td>  <?php echo $author["last_name"]; ?></td>
        <td>  <?php echo $author["birthday"]; ?></td>
        <td>  <?php echo $author["gender"]; ?></td>
        <td>  <?php echo $author["place_of_birth"]; ?></td>
        <td>
          
            <form action="/delete-author/<?php echo $author["id"]; ?>" method="POST">
                <button type="submit">Delete</button>  
            </form>
        
        </td>
    </tr>
  <?php endforeach; ?>
</table>

<div class="pagination">
    <?php for ($i = 1; $i <= $meta["total_pages"]; ++$i): ?>
        <a href="/authors?page=<?php echo $i ?>"><?php echo $i ?></a>
    <?php endfor; ?>
</div>

<?php endif; ?>